DELETE http://localhost:8000/delete-item/5
Accept: application/json

###
PATCH http://localhost:8000/update-item/2
Content-Type: application/json

{
  "product_quantity": 1
}

###
GET http://localhost:8000/cart-items/
Accept: application/json

###
POST http://localhost:8000/cart-items/
Content-Type: application/json

{
  "product_name": "MacBook",
  "product_price": 2000,
  "product_quantity": 42
}



